FROM mcr.microsoft.com/dotnet/sdk:5.0 as builder
COPY . /app
WORKDIR /app
RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]
RUN ["dotnet", "publish", "--configuration","Release", "--output","out"] 

FROM mcr.microsoft.com/dotnet/aspnet:5.0.8-focal-amd64
WORKDIR /app
COPY --from=builder /app/out .
cmd ls -la
ENTRYPOINT ["dotnet", "sample-app.dll"]
